# Generated by Django 4.0.6 on 2022-08-01 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordem',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ordem',
            name='data_pedido_enviado',
        ),
        migrations.RemoveField(
            model_name='ordem',
            name='produtos_itens',
        ),
        migrations.RemoveField(
            model_name='ordemitem',
            name='cliente',
        ),
        migrations.AddField(
            model_name='ordem',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemitem',
            name='data_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemitem',
            name='ordem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.ordem'),
        ),
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data_pedido',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ordemitem',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='ordemitem',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
