# Generated by Django 4.0.6 on 2022-08-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_ordem_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordem',
            old_name='status',
            new_name='enviado',
        ),
        migrations.RemoveField(
            model_name='ordemitem',
            name='status',
        ),
    ]
