# Generated by Django 4.0.6 on 2022-09-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0002_ordem_supermarket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
