# Generated by Django 4.0.6 on 2022-09-15 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("produtos", "0003_alter_produto_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produto",
            options={"ordering": ["expiration_date"]},
        ),
        migrations.AddField(
            model_name="categoria",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="supermarket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.lojista",
            ),
        ),
    ]
