# Generated by Django 4.0.6 on 2022-07-28 03:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
