# Generated by Django 4.0.6 on 2022-08-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_rename_status_ordem_enviado_remove_ordemitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(default=12, unique=True),
            preserve_default=False,
        ),
    ]
