# Generated by Django 4.0.6 on 2022-08-11 17:37

from django.db import migrations, models
import produtos.random_number


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemitem',
            name='number_order',
            field=models.CharField(default=produtos.random_number.random_number, max_length=14, unique=True),
        ),
    ]
