# Generated by Django 4.0.6 on 2022-08-11 17:39

from django.db import migrations, models
import produtos.random_number


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_ordemitem_number_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordem',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='ordemitem',
            name='number_order',
        ),
        migrations.AddField(
            model_name='ordem',
            name='number_order',
            field=models.CharField(default=produtos.random_number.random_number, max_length=14, unique=True),
        ),
    ]
