# Generated by Django 4.0.6 on 2022-08-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_ordemitem_ordem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemitem',
            name='data_add',
        ),
    ]
