# Generated by Django 4.0.6 on 2022-08-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_remove_ordemitem_data_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemitem',
            name='data_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
