# Generated by Django 4.0.6 on 2022-08-12 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_ordemitem_data_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='produto_nome',
            new_name='product',
        ),
    ]
