# Generated by Django 4.0.6 on 2022-08-12 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_rename_produto_nome_produto_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='price',
        ),
    ]
