# Generated by Django 4.0.6 on 2022-08-12 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_rename_quantidade_em_estoque_produto_qnt_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='quantidade_vendida',
            new_name='sold',
        ),
    ]
