# Generated by Django 4.0.6 on 2022-08-12 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_rename_categoria_produto_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricao',
            new_name='description',
        ),
    ]
