# Generated by Django 4.0.6 on 2022-08-12 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0017_rename_descricao_produto_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordem',
            old_name='data_pedido',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='ordem',
            old_name='enviado',
            new_name='ordered',
        ),
        migrations.RenameField(
            model_name='ordemitem',
            old_name='ordem',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='ordemitem',
            old_name='produto',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='product',
            new_name='name',
        ),
    ]
