# Generated by Django 4.0.6 on 2022-08-12 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0018_rename_data_pedido_ordem_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemitem',
            old_name='quantidade',
            new_name='quantity',
        ),
    ]
